### ISSUE TITLE
Question: Why rollup over esbuild?

### ISSUE THREAD

**Issue by privatenumber** [antfu/export-size-action#4]
I saw this was using [rollup](https://github.com/antfu/export-size-action/blob/main/src/size.ts#L33) via export-size but that export-size also supports [esbuild](https://github.com/antfu/export-size/blob/main/src/index.ts#L87) as a bundler.

Given esbuild is faster, was there a reason why rollup is used instead?

**Comment by antfu** [comment]
The size of minfied result from esbuild is slightly bigger, and there is some situation that esbuild binaries mess up with different versions. And overall, speed on CI is not that sensitive.

**Comment by antfu** [comment]
Humm but an option for that is definitely good to have , which I planned but forgot I guess 😅

**Comment by privatenumber** [comment]
Gotcha, thanks for explaining!

I'm working on a fork so maybe I can tackle that and PR it in later.
